sync:
  enabled: true
  recreate-connectors: true

  source:
    host: 127.0.0.1
    port: 54321
    database: test
    user: kingbase
    password: 123456
    plugin-name: decoderbufs
    snapshot-mode: initial
    slot-name: dbz_kingbase_slot
    slot-drop-on-stop: false
    init-slot: true
    recreate-slot: false
    apply-replica-identity-full: true
    replica-identity-full-fail-fast: false
    server-name: kingbase_server
    source-connector-name: kb-source
    include-tables: form.t_order,public.user_info
    include-schemas: form,public

  doris:
    jdbc-url: jdbc:mysql://127.0.0.1:9030/?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    user: root
    password: ""
    auto-create-tables: true
    drop-tables-before-sync: true
    route-mode: schema_table
    database: cdc
    database-prefix: cdc_
    table-prefix: ""
    table-suffix: ""
    schema-table-separator: "__"
    buckets: 10
    replication-num: 1

  kafka-connect:
    connect-url: http://127.0.0.1:8083
    sink-connector-name: doris-sink
    sink-tasks-max: 1
    doris-fe-nodes: 127.0.0.1
    doris-http-port: 8030
    doris-query-port: 9030
    buffer-count-records: 10000
    buffer-flush-time-ms: 1000
    max-retries: 3

